openapi: 3.0.0
info:
  title: Combined API Documentation
  version: 1.0.0
servers:
  - url: https://dashboard.sms2u.io
security:
  - bearerAuth: []
paths:
  /api/webhook/SECRET_KEY/PHONE_NO:
    $ref: paths/api_webhook_SECRET_KEY_PHONE_NO.yaml
  /api/webhook/SECRET_KEY/numberAndMessageList:
    $ref: paths/api_webhook_SECRET_KEY_numberAndMessageList.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
